import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowUpRight, CalendarRange, Users } from 'lucide-react';
import { SectionHeading } from '@/components/common/section-heading';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { dashboardMetrics, resultRows, sessionRows } from '@/data/mock';
export function DashboardPage() {
    return (_jsxs("div", { className: "space-y-8", children: [_jsx(SectionHeading, { eyebrow: "Dashboard", title: "Assessment overview", description: "Track active sessions, completions, and recent outcomes from a single premium workspace." }), _jsx("div", { className: "grid gap-4 md:grid-cols-2 xl:grid-cols-4", children: dashboardMetrics.map((metric) => (_jsxs(Card, { className: "bg-white/80", children: [_jsxs(CardHeader, { children: [_jsx(CardDescription, { children: metric.label }), _jsx(CardTitle, { className: "text-4xl", children: metric.value })] }), _jsx(CardContent, { className: "pt-0 text-sm text-slate-500", children: metric.meta })] }, metric.label))) }), _jsxs("div", { className: "grid gap-6 xl:grid-cols-[1.2fr_0.8fr]", children: [_jsxs(Card, { className: "bg-white/80", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Live sessions" }), _jsx(CardDescription, { children: "Session health, delivery status, and participant completion snapshot." })] }), _jsx(CardContent, { className: "space-y-4", children: sessionRows.map((session) => (_jsxs("div", { className: "flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-4 md:flex-row md:items-center md:justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium text-slate-950", children: session.title }), _jsxs("p", { className: "mt-1 text-sm text-slate-500", children: [session.testType, " assessment"] })] }), _jsxs("div", { className: "flex items-center gap-3 text-sm text-slate-500", children: [_jsx(Badge, { children: session.status }), _jsxs("span", { children: [session.completed, "/", session.participants, " completed"] }), _jsx(ArrowUpRight, { className: "h-4 w-4 text-slate-400" })] })] }, session.id))) })] }), _jsxs(Card, { className: "bg-white/80", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Recent completions" }), _jsx(CardDescription, { children: "Latest participants who finished an assessment." })] }), _jsxs(CardContent, { className: "space-y-4", children: [resultRows.map((result) => (_jsx("div", { className: "rounded-2xl border border-slate-200 bg-white p-4", children: _jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { children: [_jsx("p", { className: "font-medium", children: result.participantName }), _jsx("p", { className: "mt-1 text-sm text-slate-500", children: result.summary })] }), _jsx(Badge, { children: result.testType })] }) }, result.id))), _jsxs("div", { className: "grid grid-cols-2 gap-3 pt-2 text-sm text-slate-500", children: [_jsxs("div", { className: "rounded-2xl border border-slate-200 bg-white p-4", children: [_jsx(Users, { className: "mb-3 h-4 w-4" }), "94 completed assessments"] }), _jsxs("div", { className: "rounded-2xl border border-slate-200 bg-white p-4", children: [_jsx(CalendarRange, { className: "mb-3 h-4 w-4" }), "12 scheduled sessions"] })] })] })] })] })] }));
}
