import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search } from 'lucide-react';
import { SectionHeading } from '@/components/common/section-heading';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { participantRows } from '@/data/mock';
export function ParticipantsPage() {
    return (_jsxs("div", { className: "space-y-8", children: [_jsx(SectionHeading, { eyebrow: "Participants", title: "Participant directory", description: "Search and monitor participant identities, assigned tests, and completion status." }), _jsx(Card, { className: "bg-white/80", children: _jsxs(CardContent, { className: "p-5", children: [_jsxs("div", { className: "relative max-w-md", children: [_jsx(Search, { className: "pointer-events-none absolute left-4 top-3.5 h-4 w-4 text-slate-400" }), _jsx(Input, { className: "pl-10", placeholder: "Search participant name" })] }), _jsx("div", { className: "mt-6 overflow-hidden rounded-2xl border border-slate-200", children: _jsxs("table", { className: "min-w-full divide-y divide-slate-200 text-left text-sm", children: [_jsx("thead", { className: "bg-slate-50 text-slate-500", children: _jsxs("tr", { children: [_jsx("th", { className: "px-4 py-3 font-medium", children: "Participant" }), _jsx("th", { className: "px-4 py-3 font-medium", children: "Department" }), _jsx("th", { className: "px-4 py-3 font-medium", children: "Test" }), _jsx("th", { className: "px-4 py-3 font-medium", children: "Status" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-100 bg-white", children: participantRows.map((participant) => (_jsxs("tr", { children: [_jsx("td", { className: "px-4 py-4", children: _jsxs("div", { children: [_jsx("p", { className: "font-medium text-slate-950", children: participant.fullName }), _jsx("p", { className: "text-slate-500", children: participant.position })] }) }), _jsx("td", { className: "px-4 py-4 text-slate-500", children: participant.department }), _jsx("td", { className: "px-4 py-4 text-slate-500", children: participant.testType }), _jsx("td", { className: "px-4 py-4", children: _jsx(Badge, { children: participant.status }) })] }, participant.id))) })] }) })] }) })] }));
}
