import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
export function ParticipantIdentityPage() {
    const { token = 'disc-batch-a' } = useParams();
    return (_jsxs(Card, { className: "mx-auto w-full max-w-3xl bg-white/82", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "Participant identity" }), _jsx(CardDescription, { children: "Fill in your basic information before starting the assessment session." })] }), _jsxs(CardContent, { className: "space-y-6", children: [_jsxs("div", { className: "grid gap-4 md:grid-cols-2", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium text-slate-600", children: "Full name" }), _jsx(Input, { placeholder: "Full name" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium text-slate-600", children: "Email" }), _jsx(Input, { type: "email", placeholder: "name@company.com" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium text-slate-600", children: "Employee ID" }), _jsx(Input, { placeholder: "Optional code" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-sm font-medium text-slate-600", children: "Department" }), _jsx(Input, { placeholder: "Department" })] }), _jsxs("div", { className: "space-y-2 md:col-span-2", children: [_jsx("label", { className: "text-sm font-medium text-slate-600", children: "Position" }), _jsx(Input, { placeholder: "Current position" })] })] }), _jsxs("div", { className: "flex flex-col gap-3 sm:flex-row sm:justify-end", children: [_jsx(Button, { variant: "secondary", children: "Save draft" }), _jsx(Button, { asChild: true, children: _jsx(Link, { to: `/t/${token}/instructions`, children: "Continue" }) })] })] })] }));
}
