import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { discPreviewQuestions } from '@/data/mock';
export function ParticipantTestPage() {
    const { token = 'disc-batch-a' } = useParams();
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs(Card, { className: "bg-white/82", children: [_jsxs(CardHeader, { children: [_jsx(CardTitle, { children: "DISC Assessment" }), _jsx(CardDescription, { children: "Question 1 of 24 \u2022 Estimated duration 15 minutes" })] }), _jsxs(CardContent, { className: "space-y-3", children: [_jsx(Progress, { value: 12 }), _jsxs("div", { className: "flex items-center justify-between text-sm text-slate-500", children: [_jsx("span", { children: "12% complete" }), _jsx("span", { children: "14:32 remaining" })] })] })] }), discPreviewQuestions.map((question, index) => (_jsxs(Card, { className: "bg-white/82", children: [_jsxs(CardHeader, { children: [_jsxs(CardTitle, { children: ["Question ", index + 1] }), _jsx(CardDescription, { children: question.instruction })] }), _jsx(CardContent, { className: "grid gap-3", children: question.options.map((option, optionIndex) => (_jsxs("button", { type: "button", className: "flex items-center justify-between rounded-2xl border border-slate-200 bg-white px-4 py-4 text-left text-sm text-slate-600 transition hover:border-slate-300 hover:bg-slate-50", children: [_jsx("span", { children: option }), _jsx("span", { className: "text-xs font-medium uppercase tracking-[0.2em] text-slate-400", children: String.fromCharCode(65 + optionIndex) })] }, option))) })] }, question.code))), _jsx("div", { className: "sticky bottom-4 flex justify-end", children: _jsx(Button, { size: "lg", className: "shadow-panel", asChild: true, children: _jsx(Link, { to: `/t/${token}/completed`, children: "Submit responses" }) }) })] }));
}
